[package]
edition = "2021"
name = "simplersble-examples"
version = "0.0.0"

[[bin]]
name = "list_adapters"

[[bin]]
name = "scan"

[[bin]]
name = "connect"

[dependencies]
simplersble = { path = "../.." }