version: 2
build:
  os: "ubuntu-20.04"
  tools:
    python: "3.10"
  jobs:
    post_checkout:
      - echo "Command run at 'post_checkout' step"
    pre_system_dependencies:
      - echo "Command run at 'pre_system_dependencies' step"
      - sudo apt install -Y libdbus-1-dev
    post_system_dependencies:
      - echo "Command run at 'post_system_dependencies' step"
    pre_create_environment:
      - echo "Command run at 'pre_create_environment' step"
    post_create_environment:
      - echo "Command run at 'post_create_environment' step"
    pre_install:
      - echo "Command run at 'pre_install' step"
    post_install:
      - echo "Command run at 'post_install' step"
    pre_build:
      - echo "Command run at 'pre_build' step"
    post_build:
      - echo "Command run at 'post_build' step"
