name: Android Release

on:
  workflow_dispatch:

jobs:
  build-aar:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Build simpleble-bridge & simpledroidble AARs
        working-directory: ./simpledroidble
        run: |
          ./gradlew simpleble-bridge:bundleReleaseAar \
                    simpledroidble:bundleReleaseAar   \
                    --no-daemon                       \
                    -PbuildDir="${{ github.workspace }}"

      - name: Upload simpleble-bridge & simpledroidble AARs to job
        uses: actions/upload-artifact@v4
        with:
          name: simpleble-android-release
          path: outputs/aar/*.aar

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          file: outputs/aar/*.aar
          overwrite: true
          file_glob: true
