name: CI Build Libs

on: [push, pull_request]

jobs:

  # ------------------------------------------------------------
  build-windows:
    runs-on: windows-2022

    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        arch: [Win32, x64]
        sdk: ["10.0.19041.0", "10.0.22000.0"]

    steps:
    - name: Clone Repository
      uses: actions/checkout@v3
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1
    - name: Compile SimpleBLE
      run: |
        cmake -B %GITHUB_WORKSPACE%\build -G "Visual Studio 17 2022" -A ${{ matrix.arch }} -DCMAKE_SYSTEM_VERSION=${{ matrix.sdk }} -S %GITHUB_WORKSPACE%/simpleble
        cmake --build %GITHUB_WORKSPACE%\build --config Release --parallel 4
        cmake --install %GITHUB_WORKSPACE%\build --prefix %GITHUB_WORKSPACE%\build\install
      shell: cmd

  # ------------------------------------------------------------

  build-macos:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        os: [macos-11, macos-12]
        arch: [arm64, x86_64]

    steps:
    - name: Clone Repository
      uses: actions/checkout@v3
    - name: Setup Cmake
      uses: jwlawson/actions-setup-cmake@v1.13
      with:
        cmake-version: '3.21'
    - name: Compile SimpleBLE
      run: |
        cmake -B $GITHUB_WORKSPACE/build -DCMAKE_OSX_ARCHITECTURES="${{ matrix.arch }}" -DCMAKE_BUILD_TYPE=Release -S $GITHUB_WORKSPACE/simpleble
        cmake --build $GITHUB_WORKSPACE/build --config Release --parallel 4
        cmake --install $GITHUB_WORKSPACE/build --prefix $GITHUB_WORKSPACE/build/install

  # ------------------------------------------------------------

  build-linux:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04]

    steps:
    - name: Clone Repository
      uses: actions/checkout@v3
    - name: Install Dependencies
      run: |
        sudo -H apt-get update -y
        sudo -H apt-get install -y libdbus-1-dev
      env:
        DEBIAN_FRONTEND: noninteractive
    - name: Setup Cmake
      uses: jwlawson/actions-setup-cmake@v1.13
      with:
        cmake-version: '3.21'
    - name:  Compile SimpleBLE for Ubuntu
      run: |
        cmake -B $GITHUB_WORKSPACE/build_simpleble -DCMAKE_BUILD_TYPE=Release -S $GITHUB_WORKSPACE/simpleble
        cmake --build $GITHUB_WORKSPACE/build_simpleble --config Release --parallel 4
        cmake --install $GITHUB_WORKSPACE/build_simpleble --prefix $GITHUB_WORKSPACE/build_simpleble/install
    - name:  Compile SimpleBluez for Ubuntu
      run: |
        cmake -B $GITHUB_WORKSPACE/build_simplebluez -DCMAKE_BUILD_TYPE=Release -S $GITHUB_WORKSPACE/simplebluez
        cmake --build $GITHUB_WORKSPACE/build_simplebluez --config Release --parallel 4
        cmake --install $GITHUB_WORKSPACE/build_simplebluez --prefix $GITHUB_WORKSPACE/build_simplebluez/install
    - name:  Compile SimpleDBus for Ubuntu
      run: |
        cmake -B $GITHUB_WORKSPACE/build_simpledbus -DCMAKE_BUILD_TYPE=Release -S $GITHUB_WORKSPACE/simpledbus
        cmake --build $GITHUB_WORKSPACE/build_simpledbus --config Release --parallel 4
        cmake --install $GITHUB_WORKSPACE/build_simpledbus --prefix $GITHUB_WORKSPACE/build_simpledbus/install
