name: PyPI Test Release

on: [push, pull_request]

jobs:
  build_wheels:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-22.04 , windows-2022, macos-11]
        py: ["cp37-*", "cp38-*", "cp39-*", "cp310-*", "cp311-*"]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        if: runner.os == 'Linux'
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
          cache: "pip"

      - name: Install dependencies
        run: pip install -r simplepyble/requirements.txt

      - name: Build wheel
        uses: pypa/cibuildwheel@v2.9.0
        env:
          CIBW_BUILD: ${{ matrix.py }}
          CIBW_BUILD_VERBOSITY: 3
          CIBW_BEFORE_ALL_LINUX: "yum update -y && yum group install -y \"Development Tools\" && yum install -y dbus-devel"
          CIBW_ARCHS_LINUX: x86_64 i686 aarch64
          CIBW_ARCHS_MACOS: x86_64 universal2 arm64
          CIBW_ARCHS_WINDOWS: AMD64 x86
          CIBW_SKIP: "*musllinux_* pp*"
        with:
            package-dir: simplepyble

      - name: Upload wheels
        uses: actions/upload-artifact@v3
        with:
          name: simpleble-wheels
          path: wheelhouse

      - name: Check Packages
        run: twine check wheelhouse/*.whl

      - name: Publish packages
        run: twine upload --repository testpypi --skip-existing wheelhouse/*.whl --verbose
        env:
          TWINE_USERNAME: ${{ secrets.TEST_PYPI_USER }}
          TWINE_PASSWORD: ${{ secrets.TEST_PYPI_PASSWORD }}
